DOCKER-450 [Add] Support for Alfresco v23.1 && v23.2
xenit-eu/docker-alfresco pull request #208
Opened 2024-04-26 12:08 UTC by codingBenVdS

DOCKER-450 [Add] Support for Alfresco v23.1 && v23.2
  * [Add] tomcat-embedded V10
  * [TODO] Add postgres V15
Ticket: https://xenitsupport.jira.com/browse/DOCKER-450

2024-05-27 17:24 UTC, thijslemmens commented on 2repository/23.1/community-23.1.0/overload.gradle
> +    psqlimage = 'docker.io/xenit/postgres:13'
Yes, or the latest. We don't maintain this image anymore. Better move to the official image.

2024-05-27 17:26 UTC, thijslemmens requested changes
Use the official PostgreSQL images. Remove the Jackson dependency now it is bundled in our logging library

2024-05-31 09:32 UTC, codingBenVdS commented on 2repository/23.1/community-23.1.0/overload.gradle
> +    psqlimage = 'docker.io/xenit/postgres:13'
Using now the postgres:15 image

2024-06-03 12:43 UTC, thijslemmens requested changes
Not sure why you need 3 versions of TomcatFactory now, we only used one in the passed. You should at most have 2?

2024-06-03 12:43 UTC, thijslemmens commented on tomcat-base/build.gradle
> +                srcDir file("$project.projectDir/src/shared/main/java")
Why did you add this? Could have just put it in main instead of shared/main?

2024-06-10 13:40 UTC, thijslemmens approved these changes

2024-06-10 13:55 UTC, merged