DOCKER-311 Raise requirements for chown in 90-init-alfresco.sh
xenit-eu/docker-alfresco pull request #50
Opened 2020-09-22 13:28 UTC by RVanhuysseXenit

Recent experience (USGBE, refer to @rschev ) has pointed out that mounting a large, existing
alf_data with incorrect permissions/ownership resulted in a very
extensive chown. The prefered solution would have been to fix the issue
through changes to the users/groups on the host, or even to the user
set in the image/container.

This change adds an additional check on permissions, and a check on
whether the alf_data folder is too big to be effeciently chowned. The
size check is set to 10000 items in the dir by default, but can be changed through
an environment variable.

The change will allow the acting operator to decide on the correct solution

2020-09-22 14:00 UTC, vierbergenlars commented
I don't think it is a good solution to pick an arbitrary value for when to chown or not.

The chown is already there for a long time (I lost track of it in a commit from 2017), so the question is what purpose does it serve?

Starting up Alfresco with a non-writable contentstore is bad, because everything will work fine until new content is created, which fails. This will only be discovered some time after the system is started up, which is bad.

To resolve this problem, I see 2 options:
 * chown everything on startup when permissions are incorrect
 * check permissions and exit with an error when permissions are incorrect

Doing different actions based on the amount of content that is present may lead to unexpected behavior, and this construction looks considerably more complex.

2020-09-22 15:10 UTC, RVanhuysseXenit reviewed
> I don't think it is a good solution to pick an arbitrary value for when to chown or not.
> 
> The chown is already there for a long time (I lost track of it in a commit from 2017), so the question is what purpose does it serve?
> 
> Starting up Alfresco with a non-writable contentstore is bad, because everything will work fine until new content is created, which fails. This will only be discovered some time after the system is started up, which is bad.
> 
> To resolve this problem, I see 2 options:
> 
>     * chown everything on startup when permissions are incorrect
> 
>     * check permissions and exit with an error when permissions are incorrect
> 
> 
> Doing different actions based on the amount of content that is present may lead to unexpected behavior, and this construction looks considerably more complex.

It is hard to say when the wait on a chown changes from tolerable to problematic. Roel mentioned on slack that a clean slate contentstore would probably contain less than 2K entries. From there we considered that 5~10K entries would still have an okay runtime, so they could just keep the existing behaviour
But massive contentstores like longrunning production environments will currently execute that chown without warning or intervention potentially leading to problematic waittimes and resource usage.
The changes aim to introduce a check -which I've made configuratble, an exit with error code when the check is hit, and an option to overrule/disregard the check. 
I'd think this covers the second proposed solution, as it introduces the error exit, but it retains a degree of freedom for smaller systems that are not affected by the problem.
The first proposed solution looks to me like the situation as-is, and therefore the problem with large systems is still present.
I can see how removing the check on content can simplify the script, but it removes the old behaviour completely, and I think it could lead to frustration in dev and test environments?

2020-09-22 15:14 UTC, WimCrols commented
> I don't think it is a good solution to pick an arbitrary value for when to chown or not.
> 
> The chown is already there for a long time (I lost track of it in a commit from 2017), so the question is what purpose does it serve?
> 
> Starting up Alfresco with a non-writable contentstore is bad, because everything will work fine until new content is created, which fails. This will only be discovered some time after the system is started up, which is bad.
> 
> To resolve this problem, I see 2 options:
> 
> * chown everything on startup when permissions are incorrect
> * check permissions and exit with an error when permissions are incorrect
> 
> Doing different actions based on the amount of content that is present may lead to unexpected behavior, and this construction looks considerably more complex.

When we discussed this IRL I also said this: do not check, bail out early with an error. Maybe that wasn't clear enough. The responsibility should be left with the caller, not the script IMO.

2020-09-22 15:24 UTC, vierbergenlars commented
> I can see how removing the check on content can simplify the script, but it removes the old behaviour completely, and I think it could lead to frustration in dev and test environments?

Not doing a chown may indeed be a problem when starting a fresh Alfresco with a volume, which is used all the time during development.
To make that work, we may need to `chown` just the root folder. The content store is an empty folder at that point in time.
However, if we do a `chown` on the root folder, we lose the ability to detect the content store ownership problem on the next startup.

I did not test this scenario out, but please do when you make changes.

2020-09-22 15:25 UTC, RVanhuysseXenit commented
> > I don't think it is a good solution to pick an arbitrary value for when to chown or not.
> > The chown is already there for a long time (I lost track of it in a commit from 2017), so the question is what purpose does it serve?
> > Starting up Alfresco with a non-writable contentstore is bad, because everything will work fine until new content is created, which fails. This will only be discovered some time after the system is started up, which is bad.
> > To resolve this problem, I see 2 options:
> > 
> > * chown everything on startup when permissions are incorrect
> > * check permissions and exit with an error when permissions are incorrect
> > 
> > Doing different actions based on the amount of content that is present may lead to unexpected behavior, and this construction looks considerably more complex.
> 
> When we discussed this IRL I also said this: do not check, bail out early with an error. In other words, Lars' 2nd solution. Maybe that wasn't clear enough.
> The responsibility should be left with the caller, not the script IMO.

Comments on the ticket deviate.
I guess I'll simplify.

2020-09-23 06:56 UTC, WimCrols commented
> Comments on the ticket deviate.
> I guess I'll simplify.
If it's too unclear, we can always do a quick call

2020-09-23 13:46 UTC, RVanhuysseXenit commented on src/main/resources/global/90-init-alfresco.sh
> -  if [[ $(stat -c %U /opt/alfresco/alf_data) != "$user" ]]; then
Check on content & content.delete, if they exist/

2020-09-24 08:14 UTC, rschev commented on src/main/resources/global/90-init-alfresco.sh
> +   && ($(stat -c %U /opt/alfresco/alf_data) != "$user" && $(stat -c %a /opt/alfresco/alf_data) -lt 766) ]]; then
First, we should check for /opt/alfresco/alf_data/contentstore.deleted as well, we need both to be present.
Second, I think this should be `stat -c %U /opt/alfresco/alf_data/contentstore`, and likewise for `stat -c %a` and for `contentstore.deleted`. We don't need permissions on alf_data itself if both contentstore and contentstore.deleted exist and we have permissions on them.

2020-09-24 08:21 UTC, WimCrols commented on src/main/resources/global/90-init-alfresco.sh
> +    echo "No contentstore in alf_data, chowning directory to tomcat user."
As I proposed yesterday, it's important that people understand the **why** and this is more the **what**. Suggestion:
echo "No contentstore found in alf_data -> Assuming development scenario -> Chowning directory to tomcat user."

2020-09-24 08:23 UTC, WimCrols commented on src/main/resources/global/90-init-alfresco.sh
> +    echo "No contentstore in alf_data, chowning directory to tomcat user."
The comment at l36 for instance, does explain it well.

2020-09-24 10:09 UTC, WimCrols commented
Looks good to me :shipit: but I'll leave the official approval to docker peeps.

2020-09-24 11:28 UTC, vierbergenlars requested changes

2020-09-24 11:28 UTC, vierbergenlars commented on src/main/resources/global/90-init-alfresco.sh
> +     && ($(stat -c %U /opt/alfresco/alf_data/contentstore.deleted) != "$user" && $(stat -c %a /opt/alfresco/alf_data/contentstore.deleted) -lt 766) ]]; then
Shouldn't this be an OR? When one of contentstore and contentstore.deleted has wrong permissions, we should exit.

2020-09-25 12:11 UTC, vierbergenlars approved these changes
:shipit:

2020-09-28 06:33 UTC, rschev approved these changes

2020-09-29 08:59 UTC, merged