Xm2 c 43
xenit-eu/docker-alfresco pull request #98
Opened 2022-10-31 13:13 UTC by hechmi-dammak-xenit

2022-11-07 08:24 UTC, thijslemmens requested changes
No proper title, no description. Please fix

2022-11-15 07:36 UTC, hechmi-dammak-xenit commented on tomcat-base/src/shared/main/java/eu/xenit/alfresco/tomcat/embedded/alfresco/AlfrescoTomcatCustomizer.java
> +package eu.xenit.alfresco.tomcat.embedded.alfresco;
I think that this class should be under the tomcat package too same for shareTomcatCustomizer

2022-11-15 12:42 UTC, thijslemmens requested changes
Almost there. The README needs some attention. I tested it to work.

2022-11-15 12:42 UTC, thijslemmens commented on README.md
> +## Supported Tags for Share
This section is not up-to-date

2022-11-15 12:42 UTC, thijslemmens commented on README.md
> +* [`docker.io/xenit/share-enterprise`] = enterprise Share images
enterprise images should never go to docker.io

2022-11-15 12:42 UTC, thijslemmens commented on README.md
> +## Images created
please check and correct the full image url's. Now it is inconsistent between share and repository

2022-11-16 07:55 UTC, thijslemmens commented on README.md
> +* [`docker.io/xenit/tomcat`] = Xenit specific tomcat images
Didn't know we publish this one too, but apparently we do

2022-11-16 07:57 UTC, thijslemmens requested changes

2022-11-16 07:57 UTC, thijslemmens commented on README.md
> +* [`docker.io/xenit/docker.io/xenit/share-community`] = community Share images
please recheck. `docker.io` twice, and if I read your code, I'm expecting `alfresco-share-community`

2022-11-16 08:47 UTC, thijslemmens approved these changes

2022-11-16 08:47 UTC, merged